# 查询时是否只使用自己绑定的CK
onlySelfCk: false

# 米游社国际服代理
proxy:
  host: null
  port: null

# 使用wkhtmltoimage渲染图片
wkhtmltoimage: false

# 渲染精度(0-100)
quality: 100

# 数据库（可选sqlite、postgres）一般使用sqlite就足够满足需求
dialect: sqlite

# PostgreSQL 数据库默认配置
postgres:
  host: localhost
  port: 5432
  database: mystool
  username: postgres
  password: a123456